import type { RuleBlock } from '../types.js'
import { renderFencedBlocks } from '../render.js'

export function renderCopilotInstructions(blocks: RuleBlock[]): string {
  const header: string[] = [
    '# Copilot Instructions — Auto-generated by vibelock',
    '',
    'These instructions help GitHub Copilot understand the project stack.',
    'Do not edit content inside `<!-- vibelock:* -->` fences.',
    '',
    '---',
    '',
  ]

  return [...header, ...renderFencedBlocks(blocks)].join('\n')
}
