import type { RuleBlock } from '../types.js'
import { renderFencedBlocks } from '../render.js'

export function renderCursorRulesMdc(blocks: RuleBlock[]): string {
  const descriptions = blocks.map((b) => b.id).join(', ')

  const header: string[] = [
    '---',
    'title: vibelock — Stack Rules',
    `description: Auto-generated rules for ${descriptions}`,
    'globs: **/*',
    '---',
    '',
    '# Stack Rules (auto-generated by vibelock)',
    '',
    'Do not edit content inside `<!-- vibelock:* -->` fences.',
    '',
  ]

  return [...header, ...renderFencedBlocks(blocks)].join('\n')
}
