import type { RuleBlock } from '../types.js'
import { renderFencedBlocks } from '../render.js'

export function renderAgentsMd(blocks: RuleBlock[]): string {
  const header: string[] = [
    '# AI Agent Rules',
    '',
    'This file is partially auto-generated by vibelock.',
    'Do not edit content inside `<!-- vibelock:* -->` fences.',
    'Everything outside those fences is yours to edit freely.',
    '',
    '---',
    '',
  ]

  return [...header, ...renderFencedBlocks(blocks)].join('\n')
}

export function parseFencedSections(content: string): Map<string, string> {
  const sections = new Map<string, string>()
  const regex = /<!--\s*vibelock:(\w+)\s*-->([\s\S]*?)<!--\s*\/vibelock:\1\s*-->/g
  let match: RegExpExecArray | null

  while ((match = regex.exec(content)) !== null) {
    const id = match[1]!
    const sectionContent = match[2]!.trim()
    sections.set(id, sectionContent)
  }

  return sections
}

export function getExistingBlockIds(content: string): string[] {
  const ids: string[] = []
  const regex = /<!--\s*vibelock:(\w+)\s*-->/g
  let match: RegExpExecArray | null

  while ((match = regex.exec(content)) !== null) {
    ids.push(match[1]!)
  }

  return ids
}
