import type { RuleBlock } from '../types.js'
import { renderFencedBlocks } from '../render.js'

export function renderClaudeMd(blocks: RuleBlock[]): string {
  const header: string[] = [
    '# CLAUDE.md — Auto-generated by vibelock',
    '',
    'This file supplements AGENTS.md with tool-specific conventions.',
    'Do not edit content inside `<!-- vibelock:* -->` fences.',
    '',
    '---',
    '',
  ]

  return [...header, ...renderFencedBlocks(blocks)].join('\n')
}
