import type { RuleBlock } from '../types.js'
import { renderFencedBlocks } from '../render.js'

export function renderClaudeMd(blocks: RuleBlock[]): string {
  const header: string[] = [
    '# Project Rules & Guidelines (CLAUDE.md)',
    '',
    '> [!IMPORTANT]',
    '> This file is partially auto-generated by **vibelock**.',
    '> Do not edit any content inside `<!-- vibelock:* -->` fences, as it will be overwritten during stack drifts.',
    '> Feel free to add or modify rules and notes **outside** the fences.',
    '',
    '## 🤖 AI Agent Persona & Behavior',
    '',
    'When working on this codebase, you must adhere to these default behavioral guidelines:',
    '',
    '### 1. Decision-Making & Planning',
    '* **Ambiguity:** If a task is underspecified, stop and ask one clear, clarifying question rather than guessing.',
    '* **Planning:** For large refactors or modifications (touching >5 files), draft an implementation plan first and wait for approval.',
    '* **Safety:** Never run destructive terminal commands or delete codebase files without explicit user confirmation.',
    '',
    '### 2. Communication Style',
    '* Be extremely concise and direct in your responses.',
    '* Do not include conversational filler unless it directly adds technical context.',
    '* Always use standard markdown links with `file://` scheme to link files and directory paths.',
    '',
    '### 3. Quality Standards',
    "* Write clean, idiomatic code matching the project's existing style.",
    '* Keep functions small and single-purpose (< 50 lines).',
    '* Prefer explicit parameters over implicit variables.',
    '',
    '---',
    '',
    '## 🛠️ Stack Rules (Auto-generated)',
    '',
  ]

  return [...header, ...renderFencedBlocks(blocks)].join('\n')
}
